spring.application.name=amc
spring.datasource.url=jdbc:postgresql://127.0.0.1:5444/security_db
spring.datasource.username=postgres

#DELETE
spring.datasource.password=root
spring.security.user.name=admin
spring.security.user.password=admin


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect